# Usa un'immagine di base di Rust
FROM rust:latest

# Installa cargo-watch
RUN cargo install cargo-watch
RUN apt-get update && apt-get install libclang-dev yara libyara-dev -y

# Imposta la directory di lavoro
WORKDIR /app

# Comando di default per cargo-watch
ENTRYPOINT ["cargo", "watch", "-c", "-d", "5", "--"]

CMD ["run"]
